### ISSUE TITLE
Getting "Unknown argument type args (RuntimeError)" during code analysis

### ISSUE THREAD

**Issue by emilianodellacasa** [gregmolnar/spektr#11]
I installed spektr in my Rails project cloning the git repo:

`gem 'spektr', git: 'https://github.com/gregmolnar/spektr'`

When I run `spektr` command in the root directory, it gives me the following error:

```
[|] Initializing Done!

Checks:

Spektr::Checks::Send, Spektr::Checks::Base, Spektr::Checks::BasicAuth, Spektr::Checks::BasicAuthTiming, Spektr::Checks::CommandInjection, Spektr::Checks::ContentTagXss, Spektr::Checks::CookieSerialization, Spektr::Checks::CreateWith, Spektr::Checks::Csrf, Spektr::Checks::CsrfSetting, Spektr::Checks::DefaultRoutes, Spektr::Checks::Deserialize, Spektr::Checks::DetailedExceptions, Spektr::Checks::DigestDos, Spektr::Checks::DynamicFinders, Spektr::Checks::Evaluation, Spektr::Checks::FileAccess, Spektr::Checks::FileDisclosure, Spektr::Checks::FilterSkipping, Spektr::Checks::HeaderDos, Spektr::Checks::I18nXss, Spektr::Checks::JsonEncoding, Spektr::Checks::JsonEntityEscape, Spektr::Checks::JsonParsing, Spektr::Checks::LinkToHref, Spektr::Checks::MassAssignment, Spektr::Checks::Sqli, Spektr::Checks::Xss

[\] Loading files Done!

Rails version 7.0.4.3
Initializers  20     
Controllers   48     
Models        53     
Views         219    
Routes        1      
Lib files     12     

[|] Scanning files/home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/base.rb:138:in `model_attribute?': Unknown argument type args (RuntimeError)
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/base.rb:131:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/base.rb:129:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/base.rb:129:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/xss.rb:22:in `block (2 levels) in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/xss.rb:18:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/xss.rb:18:in `block in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/xss.rb:17:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/checks/xss.rb:17:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/app.rb:116:in `block (2 levels) in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/app.rb:115:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/app.rb:115:in `block in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/app.rb:108:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/app.rb:108:in `scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr.rb:62:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/lib/spektr/cli.rb:51:in `scan'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-8a22525546c5/bin/spektr:7:in `<top (required)>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `load'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `<main>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
```

When running in debug mode, it doesn't give much more info.

I understand this could be related to my code, but I would like to know exactly what could be the problem.

**Comment by gregmolnar** [comment]
@emilianodellacasa thanks for reporting! I fixed it on master, can you verify that it works, please?

**Comment by emilianodellacasa** [comment]
Now it gives me a different error:

```
[|] Scanning files/home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:118:in `block (2 levels) in model_attribute?': undefined method `name' for s(:lvar, :n):Parser::AST::Node (NoMethodError)

              return exp.user_input? if exp.is_a?(Exp::Ivasign) && exp.name == item.name
                                                                                   ^^^^^
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:117:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:117:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:116:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:116:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:131:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:131:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:131:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:131:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/base.rb:129:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/xss.rb:22:in `block (2 levels) in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/xss.rb:18:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/xss.rb:18:in `block in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/xss.rb:17:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/checks/xss.rb:17:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/app.rb:116:in `block (2 levels) in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/app.rb:115:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/app.rb:115:in `block in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/app.rb:108:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/app.rb:108:in `scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr.rb:62:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/lib/spektr/cli.rb:51:in `scan'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-5813968dfab8/bin/spektr:7:in `<top (required)>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `load'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `<main>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'

```

Please let me know if I can help in any way

**Comment by gregmolnar** [comment]
If you run with the `-d` flag it should tell you the file where this error happens. It would be really helpful to see the contents of that file so I can what syntax causes it. If the contents of the file can't be shared, I can try to change the scanner to output the actual line where it happens.

**Comment by emilianodellacasa** [comment]
Actually it would be better to print the line where the problem happens, because the file can't be shared and I think it could be helpful also in the future.

**Comment by gregmolnar** [comment]
Can you try to run master with the -d flag? You should see a "Checking arguments in ..." line before the exception showing the filename and line number. If you could give me the code on that line, that would help to figure out the issue.

**Comment by gregmolnar** [comment]
@emilianodellacasa sorry for the delay, but finally, I got to this issue. Can you check your app with master please?

**Comment by emilianodellacasa** [comment]
I did but I had another error, this is the log:

```
/home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/base.rb:139:in `model_attribute?': Unknown argument type begin (RuntimeError)
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/base.rb:132:in `block in model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/base.rb:130:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/base.rb:130:in `model_attribute?'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/xss.rb:23:in `block (2 levels) in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/xss.rb:19:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/xss.rb:19:in `block in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/xss.rb:17:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/checks/xss.rb:17:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/app.rb:116:in `block (2 levels) in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/app.rb:115:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/app.rb:115:in `block in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/app.rb:108:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/app.rb:108:in `scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr.rb:62:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/lib/spektr/cli.rb:51:in `scan'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-d5927ba07b08/bin/spektr:7:in `<top (required)>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `load'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `<main>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
```

And this is the code causing the problem:

```
<%=raw [ Util.config_for(:sw)[:year],
			(link_to(t(".access_to", year: Util.config_for(:switch)[:year]), Util.config_for(:switch)[:server]) unless Util.config_for(:switch)[:server].blank? or Util.config_for(:switch)[:year].blank?)
			].compact.join(" ") %></td>
```

**Comment by gregmolnar** [comment]
@emilianodellacasa are you sure it is that line? The error message mentions "begin", but I don't see any block-related code in that snippet.

**Comment by gregmolnar** [comment]
I think I fixed the underlying issue. Could you please test it when you have a chance?

**Comment by emilianodellacasa** [comment]
I have run in another error, this is the output of the command:

```
D, [2023-10-23T11:26:50.812759 #22494] DEBUG -- : Running Spektr::Checks::Xss on ./app/views/messages/index.html.erb
D, [2023-10-23T11:26:50.813381 #22494] DEBUG -- : Checking arguments in ./app/views/messages/index.html.erb at line 67
/home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/base.rb:99:in `user_input?': Unknown argument type and  s(:if, (RuntimeError)
  s(:begin,
    s(:and,
      s(:send,
        s(:lvar, :m_e), :is_a?,
        s(:const, nil, :Message)),
      s(:send,
        s(:send,
          s(:lvar, :m_e), :user), :present?))),
  s(:begin,
    s(:send,
      s(:send,
        s(:send,
          s(:lvar, :m_e), :user), :complete_name), :+,
      s(:str, "&nbsp;&rarr;"))),
  s(:begin,
    s(:send,
      s(:str, "&larr;&nbsp;"), :+,
      s(:send,
        s(:send,
          s(:const, nil, :Device), :model_name), :human))))
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/xss.rb:20:in `block (2 levels) in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/xss.rb:19:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/xss.rb:19:in `block in run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/xss.rb:17:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/checks/xss.rb:17:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/app.rb:116:in `block (2 levels) in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/app.rb:115:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/app.rb:115:in `block in scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/app.rb:108:in `each'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/app.rb:108:in `scan!'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr.rb:62:in `run'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/lib/spektr/cli.rb:51:in `scan'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bundler/gems/spektr-6244f3296273/bin/spektr:7:in `<top (required)>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `load'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/spektr:25:in `<main>'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `eval'
	from /home/emiliano/.rvm/gems/ruby-3.1.0/bin/ruby_executable_hooks:22:in `<main>'
```

And this is the line:

`<td><%=raw (m_e.is_a?(Message) and m_e.user.present?) ? (m_e.user.complete_name+"&nbsp;&rarr;") : ("&larr;&nbsp;"+Device.model_name.human) %></td>`

**Comment by gregmolnar** [comment]
@emilianodellacasa I fixed this one too. 
Thank you so much for spending the time to help me fix these!

**Comment by emilianodellacasa** [comment]
Now it works like a charm!

Thank you for your hard work and for releasing such a wonderful gem
